jasypt:
    encryptor:
        bean: encryptorBean
        password: ${JASYPT_ENCRYPTOR_PASSWORD:}

user: uli
defaultPassword: ENC(nrmZtkF7T0kjG/VodDvBw93Ct8EgjCA+)
# works with @EnableEncryptableProperties and StandardEncryptableEnvironment
endpoint: https://${user}:${defaultPassword}@localhost:30000

