jasypt:
    encryptor:
        bean: encryptorBean
        password: ${JASYPT_ENCRYPTOR_PASSWORD:password}
        property:
          filter:
            include-names:
              - ^secret2.*

secret2:
    property: '{cipherr}nrmZtkF7T0kjG/VodDvBw93Ct8EgjCA+'
