jasypt:
  encryptor:
    bean: encryptorBean
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
    property:
      prefix: "ENC@["
      suffix: "]"
secret2:
  property: ENC@[nrmZtkF7T0kjG/VodDvBw93Ct8EgjCA+]
